const SUPABASE_URL='https://ousymngnwyrgjeymaxng.supabase.co';
const SUPABASE_KEY='sb_publishable_mBNZmgLSEGinrksTendq9Q_IyKpsrCi';
const BUCKET='reports';
const form=document.getElementById('evidenceForm'),photosInput=document.getElementById('photos'),thumbs=document.getElementById('thumbs'),photosBanner=document.getElementById('photosBanner'),photosCount=document.getElementById('photosCount'),uploadMsg=document.getElementById('uploadMsg'),previewWrap=document.getElementById('previewWrap'),report=document.getElementById('report'),reportStage=document.getElementById('reportStage');
const sharePanel=document.getElementById('sharePanel'),pdfLink=document.getElementById('pdfLink'),prepareStatus=document.getElementById('prepareStatus'),readyActions=document.getElementById('readyActions'),createBtn=document.getElementById('createBtn');
let selectedFiles=[],previewUrls=[],reportUrls=[],currentPdfUrl='',currentPdfBlob=null,currentPdfName='';
function isMobile(){return /iPhone|iPad|iPod|Android/i.test(navigator.userAgent)}
function updateReportScale(){if(previewWrap.classList.contains('hidden'))return;const s=Math.min(1,Math.max(280,reportStage.clientWidth)/794);report.style.transform=`scale(${s})`;reportStage.style.height=`${1123*s}px`}
window.addEventListener('resize',updateReportScale);function revoke(a){a.forEach(u=>URL.revokeObjectURL(u));a.length=0}
function renderThumbs(){revoke(previewUrls);thumbs.innerHTML='';photosBanner.classList.toggle('empty',!selectedFiles.length);photosCount.textContent=selectedFiles.length?`${selectedFiles.length} من 4 صور`:'لم يتم اختيار صور';selectedFiles.forEach((file,index)=>{const box=document.createElement('div');box.className='thumb';const img=document.createElement('img'),url=URL.createObjectURL(file);previewUrls.push(url);img.src=url;const remove=document.createElement('button');remove.type='button';remove.textContent='×';remove.onclick=()=>{selectedFiles.splice(index,1);renderThumbs()};box.append(img,remove);thumbs.appendChild(box)})}
photosInput.onchange=()=>{const incoming=Array.from(photosInput.files||[]).filter(f=>f.type.startsWith('image/')),combined=[...selectedFiles,...incoming];uploadMsg.textContent='';if(combined.length>4){selectedFiles=combined.slice(0,4);uploadMsg.textContent='يمكن رفع 4 صور فقط. تم الاحتفاظ بأول 4 صور.'}else selectedFiles=combined;photosInput.value='';renderThumbs()};
form.addEventListener('reset',()=>{selectedFiles=[];currentPdfUrl='';currentPdfBlob=null;setTimeout(()=>{renderThumbs();previewWrap.classList.add('hidden')},0)});
function formatDate(v){if(!v)return'';const[y,m,d]=v.split('-').map(Number);return`${d} / ${m} / ${y}`}
function fillBullets(id,text){const el=document.getElementById(id);el.innerHTML='';text.split(/\n+/).map(x=>x.trim()).filter(Boolean).slice(0,6).forEach(t=>{const d=document.createElement('div');d.className='bullet-item';d.textContent=t;el.appendChild(d)})}
async function buildReport(){document.getElementById('rProgram').textContent=document.getElementById('program').value.trim();document.getElementById('rType').textContent=document.getElementById('programType').value.trim();document.getElementById('rEntity').textContent=document.getElementById('entity').value.trim();document.getElementById('rTarget').textContent=document.getElementById('target').value.trim();document.getElementById('rDate').textContent=formatDate(document.getElementById('date').value);document.getElementById('rTeacher').textContent=document.getElementById('teacher').value.trim();fillBullets('rGoals',document.getElementById('goals').value);fillBullets('rImpact',document.getElementById('impact').value);revoke(reportUrls);const pb=document.getElementById('rPhotos');pb.innerHTML='';selectedFiles.forEach((file,i)=>{const img=document.createElement('img'),u=URL.createObjectURL(file);reportUrls.push(u);img.src=u;img.alt=`شاهد ${i+1}`;pb.appendChild(img)});for(let i=selectedFiles.length;i<4;i++){const p=document.createElement('div');p.className='photo-placeholder';p.textContent='صورة شاهد';pb.appendChild(p)}previewWrap.classList.remove('hidden');requestAnimationFrame(()=>{updateReportScale();previewWrap.scrollIntoView({behavior:'smooth',block:'start'})})}
form.onsubmit=async e=>{e.preventDefault();currentPdfUrl='';currentPdfBlob=null;sharePanel.classList.add('hidden');readyActions.classList.add('hidden');prepareStatus.classList.remove('hidden');createBtn.disabled=true;const old=createBtn.textContent;createBtn.textContent='جاري التجهيز...';try{await buildReport();await new Promise(r=>setTimeout(r,150));const blob=await makePdfBlob(),up=await uploadPdf(blob);currentPdfBlob=blob;currentPdfUrl=up.url;currentPdfName=up.name;pdfLink.value=currentPdfUrl;prepareStatus.classList.add('hidden');sharePanel.classList.remove('hidden');readyActions.classList.remove('hidden')}catch(err){console.error(err);prepareStatus.innerHTML=`<strong>تعذر تجهيز PDF</strong><div>${err.message||'خطأ غير معروف'}</div>`}finally{createBtn.disabled=false;createBtn.textContent=old}};
document.getElementById('editBtn').onclick=()=>{previewWrap.classList.add('hidden');form.scrollIntoView({behavior:'smooth'})};
async function ensureExportLibs(){if(!window.html2canvas)await new Promise((r,j)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/html2canvas@1.4.1/dist/html2canvas.min.js';s.onload=r;s.onerror=j;document.head.appendChild(s)});if(!window.jspdf)await new Promise((r,j)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/jspdf@2.5.1/dist/jspdf.umd.min.js';s.onload=r;s.onerror=j;document.head.appendChild(s)})}
async function renderReportCanvas(scale=3){await ensureExportLibs();document.body.classList.add('exporting');const ot=report.style.transform,oh=reportStage.style.height;report.style.transform='none';reportStage.style.height='1123px';try{await Promise.all(Array.from(report.querySelectorAll('img')).map(img=>img.complete?Promise.resolve():new Promise(r=>{img.onload=img.onerror=r})));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return await html2canvas(report,{scale,useCORS:true,backgroundColor:'#fff',logging:false,width:794,height:1123,windowWidth:1200,windowHeight:1400})}finally{report.style.transform=ot;reportStage.style.height=oh;document.body.classList.remove('exporting')}}
function downloadDataUrl(u,n){const a=document.createElement('a');a.download=n;a.href=u;document.body.appendChild(a);a.click();a.remove()}
document.getElementById('imageBtn').onclick=async()=>{try{const c=await renderReportCanvas(isMobile()?2:3);downloadDataUrl(c.toDataURL('image/png'),'evidence.png')}catch(e){alert('تعذر إنشاء الصورة')}};
async function makePdfBlob(){const c=await renderReportCanvas(isMobile()?2:3),jsPDF=window.jspdf.jsPDF,p=new jsPDF({orientation:'portrait',unit:'mm',format:'a4',compress:true});p.addImage(c.toDataURL('image/jpeg',.95),'JPEG',0,0,210,297,undefined,'FAST');return p.output('blob')}
async function getNextReportNumber(){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/next_report_number`,{method:'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/json'},body:'{}'}),t=await r.text();if(!r.ok)throw new Error(`RPC ${r.status}: ${t}`);return Number(JSON.parse(t))}
async function uploadPdf(blob){const n=await getNextReportNumber(),name=`evidence-${n}.pdf`,r=await fetch(`${SUPABASE_URL}/storage/v1/object/${BUCKET}/${name}`,{method:'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/pdf','x-upsert':'false'},body:blob}),t=await r.text();if(!r.ok)throw new Error(`UPLOAD ${r.status}: ${t}`);return{url:`${SUPABASE_URL}/storage/v1/object/public/${BUCKET}/${name}`,name}}
document.getElementById('printBtn').onclick=()=>currentPdfUrl&&window.open(currentPdfUrl,'_blank');document.getElementById('copyLinkBtn').onclick=async()=>{if(!currentPdfUrl)return;try{await navigator.clipboard.writeText(currentPdfUrl);alert('تم نسخ الرابط')}catch(e){pdfLink.select();document.execCommand('copy')}};document.getElementById('shareBtn').onclick=async()=>{if(!currentPdfBlob)return;const f=new File([currentPdfBlob],currentPdfName||'evidence.pdf',{type:'application/pdf'});if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[f]}))){try{await navigator.share({files:[f],title:'Evidence PDF'});return}catch(e){if(e.name==='AbortError')return}}window.open(currentPdfUrl,'_blank')};renderThumbs();