const SUPABASE_URL='https://ousymngnwyrgjeymaxng.supabase.co';
const SUPABASE_KEY='sb_publishable_mBNZmgLSEGinrksTendq9Q_IyKpsrCi';
const BUCKET='reports';
const form=document.getElementById('evidenceForm'),photosInput=document.getElementById('photos'),thumbs=document.getElementById('thumbs'),photosBanner=document.getElementById('photosBanner'),photosCount=document.getElementById('photosCount'),uploadMsg=document.getElementById('uploadMsg'),previewWrap=document.getElementById('previewWrap'),report=document.getElementById('report'),reportStage=document.getElementById('reportStage');
const sharePanel=document.getElementById('sharePanel'),pdfLink=document.getElementById('pdfLink'),prepareStatus=document.getElementById('prepareStatus'),readyActions=document.getElementById('readyActions'),createBtn=document.getElementById('createBtn');
let selectedFiles=[],previewUrls=[],reportUrls=[],currentPdfUrl='',currentPdfBlob=null,currentPdfName='';
function isMobile(){return /iPhone|iPad|iPod|Android/i.test(navigator.userAgent)}
function updateReportScale(){if(previewWrap.classList.contains('hidden'))return;const w=794,h=1123,a=Math.max(280,reportStage.clientWidth),s=Math.min(1,a/w);report.style.transform=`scale(${s})`;reportStage.style.height=`${h*s}px`}
window.addEventListener('resize',updateReportScale);function revoke(a){a.forEach(u=>URL.revokeObjectURL(u));a.length=0}
function renderThumbs(){revoke(previewUrls);thumbs.innerHTML='';photosBanner.classList.toggle('empty',!selectedFiles.length);photosCount.textContent=selectedFiles.length?`${selectedFiles.length} من 4 صور`:'لم يتم اختيار صور';selectedFiles.forEach((file,index)=>{const box=document.createElement('div');box.className='thumb';const img=document.createElement('img'),url=URL.createObjectURL(file);previewUrls.push(url);img.src=url;img.alt=`صورة شاهد ${index+1}`;const remove=document.createElement('button');remove.type='button';remove.textContent='×';remove.addEventListener('click',()=>{selectedFiles.splice(index,1);renderThumbs()});box.append(img,remove);thumbs.appendChild(box)})}
photosInput.addEventListener('change',()=>{const incoming=Array.from(photosInput.files||[]).filter(f=>f.type.startsWith('image/')),combined=[...selectedFiles,...incoming];uploadMsg.textContent='';if(combined.length>4){selectedFiles=combined.slice(0,4);uploadMsg.textContent='يمكن رفع 4 صور فقط. تم الاحتفاظ بأول 4 صور.'}else selectedFiles=combined;photosInput.value='';renderThumbs()});
form.addEventListener('reset',()=>{selectedFiles=[];currentPdfUrl='';currentPdfBlob=null;currentPdfName='';setTimeout(()=>{renderThumbs();uploadMsg.textContent='';previewWrap.classList.add('hidden');sharePanel.classList.add('hidden');readyActions.classList.add('hidden')},0)});
function formatDate(v){if(!v)return'';const[y,m,d]=v.split('-').map(Number);return`${y}/${m}/${d}`}
async function buildReport(){document.getElementById('rSchool').textContent=document.getElementById('school').value.trim();document.getElementById('rProgram').textContent=document.getElementById('program').value.trim();document.getElementById('rTeacher').textContent=document.getElementById('teacher').value.trim();document.getElementById('rTarget').textContent=document.getElementById('target').value.trim();document.getElementById('rLocation').textContent=document.getElementById('location').value.trim();document.getElementById('rCount').textContent=document.getElementById('count').value.trim();document.getElementById('rDate').textContent=formatDate(document.getElementById('date').value);const goals=document.getElementById('goals').value.split(/\n+/).map(x=>x.trim()).filter(Boolean),gb=document.getElementById('rGoals');gb.innerHTML='';goals.slice(0,6).forEach(g=>{const li=document.createElement('li');li.textContent=g;gb.appendChild(li)});revoke(reportUrls);const pb=document.getElementById('rPhotos');pb.innerHTML='';selectedFiles.forEach((file,index)=>{const img=document.createElement('img'),url=URL.createObjectURL(file);reportUrls.push(url);img.src=url;img.alt=`الشاهد المصور ${index+1}`;pb.appendChild(img)});for(let i=selectedFiles.length;i<4;i++){const p=document.createElement('div');p.className='photo-placeholder';p.textContent='صورة شاهد';pb.appendChild(p)}previewWrap.classList.remove('hidden');requestAnimationFrame(()=>{updateReportScale();previewWrap.scrollIntoView({behavior:'smooth',block:'start'})})}
form.addEventListener('submit',async e=>{e.preventDefault();currentPdfUrl='';currentPdfBlob=null;currentPdfName='';sharePanel.classList.add('hidden');readyActions.classList.add('hidden');prepareStatus.classList.remove('hidden');prepareStatus.innerHTML='<strong>جاري تجهيز ملف PDF والرابط...</strong>';createBtn.disabled=true;const old=createBtn.textContent;createBtn.textContent='جاري التجهيز...';try{await buildReport();await new Promise(r=>setTimeout(r,150));const blob=await makePdfBlob();const uploaded=await uploadPdf(blob);currentPdfBlob=blob;currentPdfUrl=uploaded.url;currentPdfName=uploaded.name;pdfLink.value=currentPdfUrl;prepareStatus.classList.add('hidden');sharePanel.classList.remove('hidden');readyActions.classList.remove('hidden')}catch(err){console.error(err);prepareStatus.innerHTML=`<strong>تعذر تجهيز PDF</strong><div style="margin-top:8px">${err.message||'خطأ غير معروف'}</div>`;readyActions.classList.add('hidden')}finally{createBtn.disabled=false;createBtn.textContent=old}});
document.getElementById('editBtn').addEventListener('click',()=>{previewWrap.classList.add('hidden');form.scrollIntoView({behavior:'smooth',block:'start'})});
async function ensureExportLibs(){if(!window.html2canvas)await new Promise((r,j)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/html2canvas@1.4.1/dist/html2canvas.min.js';s.onload=r;s.onerror=j;document.head.appendChild(s)});if(!window.jspdf)await new Promise((r,j)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/jspdf@2.5.1/dist/jspdf.umd.min.js';s.onload=r;s.onerror=j;document.head.appendChild(s)})}
async function renderReportCanvas(scale=3){await ensureExportLibs();document.body.classList.add('exporting');const ot=report.style.transform,oh=reportStage.style.height;report.style.transform='none';reportStage.style.height='1123px';try{await Promise.all(Array.from(report.querySelectorAll('img')).map(img=>img.complete?Promise.resolve():new Promise(r=>{img.onload=img.onerror=r})));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return await html2canvas(report,{scale,useCORS:true,backgroundColor:'#fff',logging:false,width:794,height:1123,windowWidth:1200,windowHeight:1400})}finally{report.style.transform=ot;reportStage.style.height=oh;document.body.classList.remove('exporting')}}
function downloadDataUrl(dataUrl,name){const a=document.createElement('a');a.download=name;a.href=dataUrl;document.body.appendChild(a);a.click();a.remove()}
document.getElementById('imageBtn').addEventListener('click',async()=>{try{const c=await renderReportCanvas(isMobile()?2:3);downloadDataUrl(c.toDataURL('image/png'),'evidence.png')}catch(e){alert('تعذر إنشاء الصورة. تأكد من اتصال الإنترنت ثم حاول مرة أخرى.')}});
async function makePdfDocument(){const canvas=await renderReportCanvas(isMobile()?2:3),{jsPDF}=window.jspdf,pdf=new jsPDF({orientation:'portrait',unit:'mm',format:'a4',compress:true});pdf.addImage(canvas.toDataURL('image/jpeg',.95),'JPEG',0,0,210,297,undefined,'FAST');return pdf}
async function makePdfBlob(){return (await makePdfDocument()).output('blob')}
async function getNextReportNumber(){const res=await fetch(`${SUPABASE_URL}/rest/v1/rpc/next_report_number`,{method:'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/json'},body:'{}'});const text=await res.text();if(!res.ok)throw new Error(`RPC ${res.status}: ${text}`);const n=Number(JSON.parse(text));if(!Number.isFinite(n))throw new Error(`Invalid report number: ${text}`);return n}
async function uploadPdf(blob){const number=await getNextReportNumber();const storageName=`evidence-${number}.pdf`;const res=await fetch(`${SUPABASE_URL}/storage/v1/object/${BUCKET}/${storageName}`,{method:'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/pdf','x-upsert':'false'},body:blob});const text=await res.text();if(!res.ok)throw new Error(`UPLOAD ${res.status}: ${text}`);return{url:`${SUPABASE_URL}/storage/v1/object/public/${BUCKET}/${storageName}`,name:storageName}}
document.getElementById('printBtn').addEventListener('click',()=>{if(!currentPdfUrl)return;window.open(currentPdfUrl,'_blank')});
document.getElementById('copyLinkBtn').addEventListener('click',async()=>{if(!currentPdfUrl)return;try{await navigator.clipboard.writeText(currentPdfUrl);alert('تم نسخ الرابط')}catch(e){pdfLink.select();document.execCommand('copy');alert('تم نسخ الرابط')}});
document.getElementById('shareBtn').addEventListener('click',async()=>{if(!currentPdfUrl||!currentPdfBlob)return;const file=new File([currentPdfBlob],currentPdfName||'evidence.pdf',{type:'application/pdf'});if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){try{await navigator.share({files:[file],title:'Evidence PDF'});return}catch(e){if(e.name==='AbortError')return}}if(navigator.share){try{await navigator.share({title:'Evidence PDF',url:currentPdfUrl});return}catch(e){if(e.name==='AbortError')return}}window.open(`https://wa.me/?text=${encodeURIComponent(currentPdfUrl)}`,'_blank')});
renderThumbs();