const SUPABASE_URL='https://ousymngnwyrgjeymaxng.supabase.co';
const SUPABASE_KEY='sb_publishable_mBNZmgLSEGinrksTendq9Q_IyKpsrCi';
const BUCKET='reports';
const form=document.getElementById('evidenceForm'),photosInput=document.getElementById('photos'),thumbs=document.getElementById('thumbs'),photosBanner=document.getElementById('photosBanner'),photosCount=document.getElementById('photosCount'),uploadMsg=document.getElementById('uploadMsg'),previewWrap=document.getElementById('previewWrap'),report=document.getElementById('report'),reportStage=document.getElementById('reportStage');
const sharePanel=document.getElementById('sharePanel'),pdfLink=document.getElementById('pdfLink'),prepareStatus=document.getElementById('prepareStatus'),readyActions=document.getElementById('readyActions'),createBtn=document.getElementById('createBtn');let selectedFiles=[],previewUrls=[],reportUrls=[],currentPdfUrl='',currentPdfBlob=null,currentPdfName='',selectedTemplate='school';
const templateBackground=document.getElementById('templateBackground'),templateSwitch=document.querySelector('.template-switch'),schoolTemplateBtn=document.getElementById('schoolTemplateBtn'),adminTemplateBtn=document.getElementById('adminTemplateBtn');
function setTemplate(type){selectedTemplate=type==='admin'?'admin':'school';const isAdmin=selectedTemplate==='admin';templateBackground.src=isAdmin?'template-admin.png':'template-school.png';templateSwitch.classList.toggle('admin',isAdmin);schoolTemplateBtn.classList.toggle('active',!isAdmin);adminTemplateBtn.classList.toggle('active',isAdmin);schoolTemplateBtn.setAttribute('aria-pressed',String(!isAdmin));adminTemplateBtn.setAttribute('aria-pressed',String(isAdmin))}
schoolTemplateBtn.onclick=()=>setTemplate('school');adminTemplateBtn.onclick=()=>setTemplate('admin');
function isMobile(){return /iPhone|iPad|iPod|Android/i.test(navigator.userAgent)}function updateReportScale(){if(previewWrap.classList.contains('hidden'))return;const s=Math.min(1,Math.max(280,reportStage.clientWidth)/794);report.style.transform=`scale(${s})`;reportStage.style.height=`${1123*s}px`}window.addEventListener('resize',updateReportScale);function revoke(a){a.forEach(u=>URL.revokeObjectURL(u));a.length=0}
function currentHijri(){try{const p=new Intl.DateTimeFormat('en-US-u-ca-islamic-umalqura',{day:'numeric',month:'numeric',year:'numeric'}).formatToParts(new Date()),g=t=>Number(p.find(x=>x.type===t)?.value);return{day:g('day'),month:g('month'),year:g('year')}}catch(e){return{day:1,month:4,year:1448}}}
function setupHijriSelectors(){const d=document.getElementById('hDay'),m=document.getElementById('hMonth'),y=document.getElementById('hYear'),now=currentHijri();d.innerHTML=Array.from({length:30},(_,i)=>`<option value="${i+1}">${i+1}</option>`).join('');const names=['محرم','صفر','ربيع الأول','ربيع الآخر','جمادى الأولى','جمادى الآخرة','رجب','شعبان','رمضان','شوال','ذو القعدة','ذو الحجة'];m.innerHTML=names.map((n,i)=>`<option value="${i+1}">${i+1} - ${n}</option>`).join('');y.innerHTML=Array.from({length:21},(_,i)=>1440+i).map(v=>`<option value="${v}">${v}</option>`).join('');d.value=now.day;m.value=now.month;y.value=now.year}
function renderHijriDate(){const d=document.getElementById('hDay').value,m=document.getElementById('hMonth').value,y=document.getElementById('hYear').value,el=document.getElementById('rDate');el.innerHTML=`<span class="date-part">${d}</span><span class="date-sep">/</span><span class="date-part">${m}</span><span class="date-sep">/</span><span class="date-part">${y}</span><span class="date-era">هـ</span>`}
function renderThumbs(){revoke(previewUrls);thumbs.innerHTML='';photosBanner.classList.toggle('empty',!selectedFiles.length);photosCount.textContent=selectedFiles.length?`${selectedFiles.length} من 4 صور`:'لم يتم اختيار صور';selectedFiles.forEach((file,index)=>{const box=document.createElement('div');box.className='thumb';const img=document.createElement('img'),url=URL.createObjectURL(file);previewUrls.push(url);img.src=url;const remove=document.createElement('button');remove.type='button';remove.textContent='×';remove.onclick=()=>{selectedFiles.splice(index,1);renderThumbs()};box.append(img,remove);thumbs.appendChild(box)})}
photosInput.onchange=()=>{const incoming=Array.from(photosInput.files||[]).filter(f=>f.type.startsWith('image/')),combined=[...selectedFiles,...incoming];uploadMsg.textContent='';if(combined.length>4){selectedFiles=combined.slice(0,4);uploadMsg.textContent='يمكن رفع 4 صور فقط. تم الاحتفاظ بأول 4 صور.'}else selectedFiles=combined;photosInput.value='';renderThumbs()};form.addEventListener('reset',()=>{selectedFiles=[];currentPdfUrl='';currentPdfBlob=null;setTimeout(()=>{renderThumbs();setupHijriSelectors();previewWrap.classList.add('hidden')},0)});
function fitText(el,max=11,min=5){el.classList.add('auto-fit');el.style.fontSize=max+'px';let size=max;while(size>min&&(el.scrollHeight>el.clientHeight+1||el.scrollWidth>el.clientWidth+1)){size-=.25;el.style.fontSize=size+'px'}return size}
function fitReportText(){['rProgram','rType','rEntity','rTarget','rTeacher'].forEach(id=>fitText(document.getElementById(id),11,5));['rGoals','rImpact'].forEach(id=>fitText(document.getElementById(id),11,5))}
function fillBullets(id,text){const el=document.getElementById(id);el.innerHTML='';text.split(/\n+/).map(x=>x.trim()).filter(Boolean).forEach(t=>{const d=document.createElement('div');d.className='bullet-item';d.textContent=t;el.appendChild(d)})}
async function buildReport(){templateBackground.src=selectedTemplate==='admin'?'template-admin.png':'template-school.png';document.getElementById('rProgram').textContent=document.getElementById('program').value.trim();document.getElementById('rType').textContent=document.getElementById('programType').value.trim();document.getElementById('rEntity').textContent=document.getElementById('entity').value.trim();document.getElementById('rTarget').textContent=document.getElementById('target').value.trim();renderHijriDate();document.getElementById('rTeacher').textContent=document.getElementById('teacher').value.trim();fillBullets('rGoals',document.getElementById('goals').value);fillBullets('rImpact',document.getElementById('impact').value);revoke(reportUrls);const pb=document.getElementById('rPhotos');pb.innerHTML='';pb.classList.toggle('four-photos',selectedFiles.length===4);if(selectedFiles.length===4){const cover=document.createElement('div');cover.className='evidence-cover';pb.appendChild(cover)}selectedFiles.forEach((file,i)=>{const img=document.createElement('img'),u=URL.createObjectURL(file);reportUrls.push(u);img.src=u;img.alt=`شاهد ${i+1}`;pb.appendChild(img)});previewWrap.classList.remove('hidden');fitReportText();requestAnimationFrame(()=>{fitReportText();updateReportScale();previewWrap.scrollIntoView({behavior:'smooth',block:'start'})})}
form.onsubmit=async e=>{e.preventDefault();currentPdfUrl='';currentPdfBlob=null;sharePanel.classList.add('hidden');readyActions.classList.add('hidden');prepareStatus.classList.remove('hidden');prepareStatus.innerHTML='<strong>جاري تجهيز ملف PDF والرابط...</strong>';createBtn.disabled=true;const old=createBtn.textContent;createBtn.textContent='جاري التجهيز...';try{await buildReport();await new Promise(r=>setTimeout(r,200));const blob=await makePdfBlob(),up=await uploadPdf(blob);currentPdfBlob=blob;currentPdfUrl=up.url;currentPdfName=up.name;pdfLink.value=currentPdfUrl;prepareStatus.classList.add('hidden');sharePanel.classList.remove('hidden');readyActions.classList.remove('hidden')}catch(err){console.error(err);prepareStatus.innerHTML=`<strong>تعذر تجهيز PDF</strong><div>${err.message||'خطأ غير معروف'}</div>`}finally{createBtn.disabled=false;createBtn.textContent=old}};
document.getElementById('editBtn').onclick=()=>{previewWrap.classList.add('hidden');form.scrollIntoView({behavior:'smooth'})};
function loadScript(src){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=()=>reject(new Error('تعذر تحميل مكتبة إنشاء PDF'));document.head.appendChild(s)})}
async function loadWithFallback(urls,test){if(test())return;let last;for(const u of urls){try{await loadScript(u);if(test())return}catch(e){last=e}}throw last||new Error('تعذر تحميل مكتبة إنشاء PDF')}
async function ensureExportLibs(){await loadWithFallback(['https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js','https://cdn.jsdelivr.net/npm/html2canvas@1.4.1/dist/html2canvas.min.js','https://unpkg.com/html2canvas@1.4.1/dist/html2canvas.min.js'],()=>!!window.html2canvas);await loadWithFallback(['https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js','https://cdn.jsdelivr.net/npm/jspdf@2.5.1/dist/jspdf.umd.min.js','https://unpkg.com/jspdf@2.5.1/dist/jspdf.umd.min.js'],()=>!!(window.jspdf&&window.jspdf.jsPDF))}
async function renderReportCanvas(scale=3){await ensureExportLibs();document.body.classList.add('exporting');const ot=report.style.transform,oh=reportStage.style.height;report.style.transform='none';reportStage.style.height='1123px';try{await Promise.all(Array.from(report.querySelectorAll('img')).map(img=>img.complete?Promise.resolve():new Promise(r=>{img.onload=img.onerror=r})));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return await html2canvas(report,{scale,useCORS:true,backgroundColor:'#fff',logging:false,width:794,height:1123,windowWidth:1200,windowHeight:1400})}finally{report.style.transform=ot;reportStage.style.height=oh;document.body.classList.remove('exporting')}}function downloadDataUrl(u,n){const a=document.createElement('a');a.download=n;a.href=u;document.body.appendChild(a);a.click();a.remove()}document.getElementById('imageBtn').onclick=async()=>{try{const c=await renderReportCanvas(isMobile()?2:3);downloadDataUrl(c.toDataURL('image/png'),'evidence.png')}catch(e){alert('تعذر إنشاء الصورة')}};async function makePdfBlob(){const c=await renderReportCanvas(isMobile()?2:3),jsPDF=window.jspdf.jsPDF,p=new jsPDF({orientation:'portrait',unit:'mm',format:'a4',compress:true});p.addImage(c.toDataURL('image/jpeg',.95),'JPEG',0,0,210,297,undefined,'FAST');return p.output('blob')}
async function getNextReportNumber(){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/next_report_number`,{method:'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/json'},body:'{}'}),t=await r.text();if(!r.ok)throw new Error(`RPC ${r.status}: ${t}`);return Number(JSON.parse(t))}async function uploadPdf(blob){const n=await getNextReportNumber(),name=`evidence-${n}.pdf`,r=await fetch(`${SUPABASE_URL}/storage/v1/object/${BUCKET}/${name}`,{method:'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/pdf','x-upsert':'false'},body:blob}),t=await r.text();if(!r.ok)throw new Error(`UPLOAD ${r.status}: ${t}`);return{url:`${SUPABASE_URL}/storage/v1/object/public/${BUCKET}/${name}`,name}}
function downloadBlob(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name||'evidence.pdf';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1500)}
document.getElementById('downloadPdfBtn').onclick=()=>{if(currentPdfBlob)downloadBlob(currentPdfBlob,currentPdfName||'evidence.pdf');else if(currentPdfUrl)window.open(currentPdfUrl,'_blank')};document.getElementById('printBtn').onclick=()=>currentPdfUrl&&window.open(currentPdfUrl,'_blank');document.getElementById('copyLinkBtn').onclick=async()=>{if(!currentPdfUrl)return;try{await navigator.clipboard.writeText(currentPdfUrl);alert('تم نسخ الرابط')}catch(e){pdfLink.select();document.execCommand('copy')}};document.getElementById('shareBtn').onclick=async()=>{if(!currentPdfBlob)return;const f=new File([currentPdfBlob],currentPdfName||'evidence.pdf',{type:'application/pdf'});if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[f]}))){try{await navigator.share({files:[f],title:'Evidence PDF'});return}catch(e){if(e.name==='AbortError')return}}window.open(currentPdfUrl,'_blank')};setTemplate('school');setupHijriSelectors();renderThumbs();